"""empty message

Revision ID: c06ebd6af7c7
Revises: 
Create Date: 2021-01-26 20:48:27.486511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c06ebd6af7c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_title'), 'text', ['title'], unique=True)
    op.create_table('key_phrase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('text_id', sa.Integer(), nullable=True),
    sa.Column('wiki_link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['text_id'], ['text.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('key_phrase')
    op.drop_index(op.f('ix_text_title'), table_name='text')
    op.drop_table('text')
    # ### end Alembic commands ###
