"""empty message

Revision ID: d1db0dc47789
Revises: 
Create Date: 2021-01-28 11:53:20.764193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1db0dc47789'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_title'), 'text', ['title'], unique=False)
    op.create_table('keyphrase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('wiki_link', sa.String(), nullable=True),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.Column('text_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['text_id'], ['text.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyphrase')
    op.drop_index(op.f('ix_text_title'), table_name='text')
    op.drop_table('text')
    # ### end Alembic commands ###
